version: "3"

services:
  # DISCOVERY SERVICE
  discovery:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - 8083:8083

  # API GATEWAY
  gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - discovery
  
  # SERVICES
  orders:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - discovery

  customers:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - discovery

 